apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications
        image: public.ecr.aws/i2g9d5i9/namespace/com.distribuidos.notifications:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: notifications
spec:
  type: LoadBalancer
  selector:
    app: notifications
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80