# Spring
server:
  port: 8080
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
spring:
  main:
    banner-mode: console
    lazy-initialization: true
---
# ENVIRONMENT
environment:
  security-disable-ssl-cert-validation: ${DISABLE_SSL_CERT_VALIDATION:false}
  operator-id: ${OPERATOR_ID:66dfa51b4d8f56001517a04c}
  operator-name: ${OPERATOR_NAME:ArchivoFiel}
  domains:
    base: https://gcp-domain
    users-domain: ${USERS_DOMAIN:${environment.domains.base}/ssh-guest-search/v1}
    centralizer-domain: ${CENTRALIZER_DOMAIN:https://govcarpeta-apis-83e1c996379d.herokuapp.com/apis}
  service-retry:
    max-attempts: ${SERVICE_RETRY_MAX_ATTEMPTS:2}
  service-name: distribuidos/authentication
  max-payload-size-in-mb: ${MAX_PAYLOAD_SIZE_IN_MB:10}
---
# R2DBC
spring:
  r2dbc:
    show-sql: true
    url: r2dbc:pool:mysql://localhost:3306/transfers
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:zeus987*}
---
# Logging
logging:
  level:
    root: info
---
# Jwt
#jwt:
 # secret: EPzuE1fY/zKURZ0eklR27ULNZTpAO51+dfDWt3iJRI7zyv+UdDjXaDlkV7X1I04r89mvdet5CAWSFkfrKv+fmg==
  #expiration: 3600000

#Email Notification
#spring:
 # mail:
  #  host: smtp.gmail.com
   # port: 587
    #username: mmunetondurango@gmail.com
    #password: apolo357
    #properties:
     # mail:
      #  smtp:
       #   auth: true
        #  starttls:
         #   enable: true

#SMS Notification
#twilio:
 #account:
  # sid: AC1aba8e53a1cb4ee54a6bb9706c488161
 #auth:
  # token: 13b8eb4af318051be6d03efc88015d37
 #phone:
  # number: +19109361179 



